.TH "LIBMORMEGIL::SERIAL" 3 "October 10, 2010" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil::serialize, libmormegil::deserialize \- offsets and points on a plane
.SH SYNOPSIS
#include <stdio.h>

#include <libmormegil/serial.hh>

int libmormegil::serialize(FILE *fp, const int64_t *data);

int libmormegil::serialize(FILE *fp, const int32_t *data);

int libmormegil::serialize(FILE *fp, const int16_t *data);

int libmormegil::serialize(FILE *fp, const uint64_t *data);

int libmormegil::serialize(FILE *fp, const uint32_t *data);

int libmormegil::serialize(FILE *fp, const uint16_t *data);

int libmormegil::serialize(FILE *fp, Coord const *data);

int libmormegil::serialize(FILE *fp, Coord64 const *data);

int libmormegil::serialize(FILE *fp, Offset const *data);

int libmormegil::serialize(FILE *fp, Offset64 const *data);

int libmormegil::deserialize(FILE *fp, int64_t *data);

int libmormegil::deserialize(FILE *fp, int32_t *data);

int libmormegil::deserialize(FILE *fp, int16_t *data);

int libmormegil::deserialize(FILE *fp, uint64_t *data);

int libmormegil::deserialize(FILE *fp, uint32_t *data);

int libmormegil::deserialize(FILE *fp, uint16_t *data);

int libmormegil::deserialize(FILE *fp, Coord *data);

int libmormegil::deserialize(FILE *fp, Coord64 *data);

int libmormegil::deserialize(FILE *fp, Offset *data);

int libmormegil::deserialize(FILE *fp, Offset64 *data);


.SH DESCRIPTION
.I libmormegil::serialize
is a family of overloaded functions providing host-endianness-independent
serialization for basic integer types and the coordinate/offset types provided
in \fIlibmormegil/Coord.hh\fP

.SH CAVEATS

These functions are not templatized.

.SH AUTHOR
Martin Read <mpread@chiark.greenend.org.uk>

.SH SEE ALSO

libmormegil(3), dice(3), libmormegil::Coord(3)
