.TH "LIBMORMEGIL::STLPRINTF" 3 "February 25, 2011" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil::stlprintf, libmormegil::vstlprintf \- sprintf-alikes for std::string
.SH SYNOPSIS
#include <libmormegil/stlprintf.hh>

.SH DESCRIPTION
The \fIlibmormegil::stlprintf\fP and \fIlibmormegil::vstlprintf\fP functions
are equivalent to the standard C library's \fIsprintf\fP and \fIvsprintf\fP
functions, but operate on the standard C++ library's \fIstd::string\fP class
rather than on C-style strings.

.SH RETURNS
Both functions return a \fIstd::string\fP object containing the formatted
output.

.SH CAVEATS
These functions are wrapped around your system's local implementation of
vsprintf.  All bugs, health hazards, and other concerns which apply to the
local vsprintf apply to these functions as well.

.SH AUTHOR
Stefan O'Rear

Amendments were made by Martin Read in order to fit into libmormegil.

.SH SEE ALSO
libmormegil(3), vsprintf(3)
