.TH LIBMORMEGIL 3 "October 12, 2010" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil \- miscellaneous support routines for game development
.SH SYNOPSIS
gcc foo.c -lmormegil

.SH DESCRIPTION
.I libmormegil
consists of a shared library and its associated header files, used by
games written by Martin Read. Please refer to the manual pages for individual
subsystems to learn more.

.SH AUTHOR
Martin Read <mpread@chiark.greenend.org.uk>

.SH SEE ALSO
dice(3), libmormegil::S20prng(3)


