.TH "LIBMORMEGIL::DIV_UP" 3 "October 10, 2010" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil::div_up \- integer divide rounding upwards
.SH SYNOPSIS
#include <libmormegil/mathops.hh>

template<typename T> T libmormegil::div_up(T orig, T divisor);

.SH DESCRIPTION
.I libmormegil::div_up
is a naively written template for upward-rounding integer division.

This function exists because not all the world is an x86, and integer to
floating point conversion is \fIpainfully\fIP awkward on at least one major
load-store architecture.

.SH RETURNS
The rounded-up result of dividing \fIorig\fP by \fIdivisor\fP.

.SH CAVEATS

Implemented as naively as possible.

May not do what you want if \fIorig\fP is negative. I happen to try to avoid
dividing negative integers anyway.

.SH AUTHOR
Martin Read <mpread@chiark.greenend.org.uk>

.SH SEE ALSO

libmormegil(3)
