.TH "LIBMORMEGIL::DIVUP" 3 "March 1, 2011" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil::divup, \- divide and round up
.SH SYNOPSIS
#include <libmormegil/divup.hh>

template <typename T> T libmormegil::divup(const T& i, const T& j);

.SH DESCRIPTION
The \fIlibmormegil::divup\fP function returns the value of \fIi\fP divided
by \fIj\fP, rounded \fIup\fP (rather than down, as integer division behaves
by default).

Its behaviour is undefined when the / operator of type \fIT\fP does not behave
like rounding-down integer division, or when \fIj\fP is negative, is undefined.

.SH BUGS

This function does not range-check its arguments and is not protected against
run-time division by zero.

.SH AUTHOR
Martin Read

.SH SEE ALSO
libmormegil(3)
