.TH "LIBMORMEGIL::HCI" 3 "April 6, 2011" "libmormegil Version 1.0" "libmormegil User Manual"
.SH NAME
libmormegil::Hci \- human-computer interface
.SH SYNOPSIS
#include <libmormegil/Hci.hh>

.SH DESCRIPTION
.I libmormegil::Hci
is an abstract base class used as the basis for \fIlibmormegil::Hci_ncu\fP,
an \fIncursesw\fP-based human-computer interface class.

.SH AUTHOR
Martin Read <mpread@chiark.greenend.org.uk>

.SH SEE ALSO

libmormegil::Hci_ncu(3)
